pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Source code is available in the Jenkins workspace'
            }
        }

        stage('Build') {
            steps {
                dir('application') {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Unit Test') {
            steps {
                dir('application') {
                    bat 'mvn test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    dir('application') {
                        bat 'mvn sonar:sonar -Dsonar.projectKey=product-api -Dsonar.projectName=product-api'
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }

    post {
        always {
            junit testResults: 'application/target/surefire-reports/*.xml',
                  allowEmptyResults: true
        }
    }
}